# Generated by Django 5.0.14 on 2026-03-26 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nombre')),
                ('sku', models.CharField(max_length=30, unique=True, verbose_name='SKU')),
                ('category', models.CharField(max_length=60, verbose_name='Categoría')),
                ('location', models.CharField(max_length=80, verbose_name='Ubicación')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio unitario')),
                ('status', models.CharField(choices=[('Disponible', 'Disponible'), ('Bajo stock', 'Bajo stock'), ('Agotado', 'Agotado')], default='Disponible', max_length=20, verbose_name='Estado')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['name'],
            },
        ),
    ]
